services:
  - type: web
    name: lungs-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: PORT
        value: 5000
    autoDeploy: true
